# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'setOutSimpleLife' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for setOutSimpleLife
pod 'HorizontalCalendar'
pod 'FSCalendar'
pod 'CULColorPicker'
pod "SwiftChart"
pod 'CalendarKit'
end
